name: Update Profile README

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Dynamic README
        uses: umutphp/github-action-dynamic-profile-page@master
        with:
          # This action expects these exact names:
          readme-file: "README.md.template"
          github-username: "sungchunn"
        env:
          # It wants the token in the environment, not the 'with' section
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
